import { Dimensions, StyleSheet } from "react-native";
import { vibesTheme } from "../../theme/vibesTheme";

export const ONBOARDING_COLORS = {
  background: vibesTheme.colors.background,
  surface: "#FFFFFF",
  text: "#2B2B2B",
  muted: "#6E6E6E",
  line: "rgba(43, 43, 43, 0.1)",
  mustard: "#E4B76E",
  coral: "#D88C7A",
  blue: "#AEBFD1",
  sage: "#BFD4B5",
  lavender: "#D9CBE8",
  cream: "#F4E8D6",
};

const { width } = Dimensions.get("window");
export const isCompactOnboardingScreen = width < 360;

export const onboardingStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: ONBOARDING_COLORS.background,
  },
  safeArea: {
    flex: 1,
  },
  keyboard: {
    flex: 1,
  },
  content: {
    flex: 1,
    paddingHorizontal: isCompactOnboardingScreen ? 18 : 24,
    paddingTop: 12,
    paddingBottom: 0,
  },
  card: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    overflow: "hidden",
    position: "relative",
    paddingHorizontal: isCompactOnboardingScreen ? 18 : 22,
    paddingTop: 16,
    paddingBottom: 12,
  },
  body: {
    flexGrow: 1,
    paddingBottom: 104,
  },
  bodyScroll: {
    flex: 1,
  },
  title: {
    color: ONBOARDING_COLORS.text,
    fontFamily: vibesTheme.fonts.medium,
    fontSize: isCompactOnboardingScreen ? 25 : 28,
    lineHeight: isCompactOnboardingScreen ? 31 : 35,
    textAlign: "left",
    marginTop: 24,
  },
  subtitle: {
    color: ONBOARDING_COLORS.muted,
    fontFamily: vibesTheme.fonts.primary,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
  },
  centeredTitle: {
    textAlign: "center",
  },
  centeredSubtitle: {
    textAlign: "center",
    alignSelf: "center",
    maxWidth: 280,
  },
  footer: {
    position: "absolute",
    left: isCompactOnboardingScreen ? 18 : 22,
    right: isCompactOnboardingScreen ? 18 : 22,
    bottom: 12,
    paddingTop: 10,
    paddingBottom: 0,
    backgroundColor: "#FFFFFF",
  },
  primaryButton: {
    minHeight: 56,
    borderRadius: 22,
    backgroundColor: ONBOARDING_COLORS.mustard,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    shadowColor: ONBOARDING_COLORS.mustard,
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
  },
  primaryButtonDisabled: {
    opacity: 0.42,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontFamily: vibesTheme.fonts.medium,
    fontSize: 16,
  },
  optionList: {
    gap: 12,
    marginTop: 26,
  },
  optionCard: {
    minHeight: 64,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(228, 183, 110, 0.22)",
    backgroundColor: "rgba(255, 255, 255, 0.86)",
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
  },
  optionCardActive: {
    borderColor: ONBOARDING_COLORS.mustard,
    backgroundColor: "rgba(228, 183, 110, 0.08)",
  },
  optionIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  optionText: {
    flex: 1,
    color: ONBOARDING_COLORS.text,
    fontFamily: vibesTheme.fonts.medium,
    fontSize: 15,
  },
  energyGrid: {
    marginTop: 36,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    rowGap: 24,
  },
  energyItem: {
    width: "31%",
    minWidth: 86,
    alignItems: "center",
  },
  energyCircle: {
    width: isCompactOnboardingScreen ? 62 : 70,
    height: isCompactOnboardingScreen ? 62 : 70,
    borderRadius: 35,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 9,
  },
  energyLabel: {
    color: ONBOARDING_COLORS.text,
    fontFamily: vibesTheme.fonts.medium,
    fontSize: 13,
    textAlign: "center",
  },
  profileWrap: {
    alignItems: "center",
    marginTop: 26,
  },
  photoPickerWrap: {
    position: "relative",
    width: isCompactOnboardingScreen ? 152 : 172,
    height: isCompactOnboardingScreen ? 152 : 172,
    alignItems: "center",
    justifyContent: "center",
  },
  photoButton: {
    width: isCompactOnboardingScreen ? 128 : 148,
    height: isCompactOnboardingScreen ? 128 : 148,
    borderRadius: 74,
    borderWidth: 2,
    borderColor: "rgba(228, 183, 110, 0.45)",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(246, 246, 244, 0.75)",
    overflow: "hidden",
  },
  photo: {
    width: "100%",
    height: "100%",
  },
  cameraBadge: {
    position: "absolute",
    right: 12,
    bottom: 14,
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(43, 43, 43, 0.66)",
  },
  fieldGroup: {
    width: "100%",
    marginTop: 30,
    gap: 14,
  },
  inputRow: {
    minHeight: 58,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(228, 183, 110, 0.24)",
    backgroundColor: "rgba(255, 255, 255, 0.86)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  textAreaRow: {
    minHeight: 92,
    alignItems: "flex-start",
    paddingTop: 16,
    paddingBottom: 14,
  },
  input: {
    flex: 1,
    color: ONBOARDING_COLORS.text,
    fontSize: 16,
    marginLeft: 12,
  },
  textAreaInput: {
    minHeight: 62,
    paddingTop: 0,
    paddingBottom: 0,
  },
  ageValue: {
    flex: 1,
    color: ONBOARDING_COLORS.text,
    fontFamily: vibesTheme.fonts.medium,
    fontSize: 16,
    marginLeft: 12,
  },
  pillGrid: {
    marginTop: 28,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  pill: {
    minHeight: 50,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: "rgba(43, 43, 43, 0.09)",
    backgroundColor: "rgba(255, 255, 255, 0.78)",
    paddingHorizontal: 17,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  pillActive: {
    borderColor: ONBOARDING_COLORS.mustard,
    backgroundColor: "rgba(228, 183, 110, 0.12)",
  },
  pillAdd: {
    borderWidth: 1.4,
    borderColor: "rgba(43, 43, 43, 0.32)",
    backgroundColor: "rgba(255, 253, 248, 0.92)",
  },
  pillText: {
    color: ONBOARDING_COLORS.text,
    fontFamily: vibesTheme.fonts.medium,
    fontSize: 14,
  },
  pillIcon: {
    marginLeft: 8,
  },
  completionWrap: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  halo: {
    position: "absolute",
    width: "92%",
    aspectRatio: 1,
    borderRadius: 999,
    backgroundColor: "rgba(228, 183, 110, 0.12)",
    shadowColor: ONBOARDING_COLORS.mustard,
    shadowOpacity: 0.22,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 0 },
  },
  completionMedia: {
    width: "100%",
    maxWidth: 330,
    aspectRatio: 1,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(17, 17, 17, 0.28)",
    paddingHorizontal: 28,
  },
  modalCard: {
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    overflow: "hidden",
  },
  modalOption: {
    minHeight: 56,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(43, 43, 43, 0.08)",
  },
  modalOptionText: {
    color: ONBOARDING_COLORS.text,
    fontFamily: vibesTheme.fonts.medium,
    fontSize: 16,
  },
  customPracticeCard: {
    borderRadius: 26,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 22,
    paddingTop: 22,
    paddingBottom: 18,
  },
  customPracticeTitle: {
    color: ONBOARDING_COLORS.text,
    fontFamily: vibesTheme.fonts.primary,
    fontSize: 27,
    lineHeight: 32,
  },
  customPracticeInput: {
    minHeight: 56,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(228, 183, 110, 0.34)",
    backgroundColor: "rgba(255, 253, 248, 0.92)",
    paddingHorizontal: 16,
    color: ONBOARDING_COLORS.text,
    fontFamily: vibesTheme.fonts.primary,
    fontSize: 17,
    marginTop: 18,
  },
  customPracticeFooter: {
    flexDirection: "row",
    gap: 12,
    marginTop: 18,
  },
  customPracticeSecondary: {
    flex: 1,
    height: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(216, 140, 122, 0.28)",
    alignItems: "center",
    justifyContent: "center",
  },
  customPracticeSecondaryText: {
    color: ONBOARDING_COLORS.coral,
    fontFamily: vibesTheme.fonts.medium,
    fontSize: 15,
  },
  customPracticePrimary: {
    flex: 1,
    height: 52,
    borderRadius: 18,
    backgroundColor: ONBOARDING_COLORS.mustard,
    alignItems: "center",
    justifyContent: "center",
  },
  customPracticePrimaryDisabled: {
    opacity: 0.45,
  },
  customPracticePrimaryText: {
    color: "#FFFFFF",
    fontFamily: vibesTheme.fonts.medium,
    fontSize: 15,
  },
});

export const toneColor = (tone: keyof Pick<
  typeof ONBOARDING_COLORS,
  "mustard" | "coral" | "blue" | "sage" | "lavender" | "cream"
>) => ONBOARDING_COLORS[tone];
