import { StyleSheet, Dimensions } from "react-native";

export const PRIMARY_COLOR = "#D2A86C";
export const SECONDARY_COLOR = "#E4B76E";
export const WHITE = "#FFFFFF";
export const GRAY = "#6E6E6E";
export const DARK_GRAY = "#3A3A3A";
export const BLACK = "#1E1E1E";
export const BG_MAIN = "#F6F6F4";
export const BG_GRADIENT = "#F3EFE8";
export const TEXT_PRIMARY = "#1E1E1E";
export const TEXT_SECONDARY = "#6E6E6E";
export const SURFACE_BUTTON = "#FFFFFF";
export const CTA_PRIMARY = "#D8B27A";
export const GLOW_HIGHLIGHT = "rgba(0, 0, 0, 0.06)";
export const BUTTON_CREAM = "#FFFFFF";
export const BUTTON_BORDER = "rgba(0, 0, 0, 0.08)";
export const WARM_SHADOW = "rgba(0, 0, 0, 0.10)";
export const SERIF_FONT = "serif";

export const ONLINE_STATUS = "#66BCA3";
export const OFFLINE_STATUS = "#E07A6F";

export const STAR_ACTIONS = "#FF9F68";
export const LIKE_ACTIONS = "#FF9F68";
export const DISLIKE_ACTIONS = "#D66A6A";
export const FLASH_ACTIONS = "#9B7EDC";

export const DIMENSION_WIDTH = Dimensions.get("window").width;
export const DIMENSION_HEIGHT = Dimensions.get("window").height;

export default StyleSheet.create({
  // COMPONENT - CARD ITEM
  containerCardItem: {
    
    borderRadius: 8,
    alignItems: "center",
    margin: 10,
    elevation: 1,
    
  },
  containerCardItemDiscover: {
    borderRadius: 24,
    alignItems: "center",
    paddingVertical: 18,
    paddingHorizontal: 22,
    marginHorizontal: 0,
    marginTop: 8,
    width: DIMENSION_WIDTH - 20,
    alignSelf: "center",
    minHeight: DIMENSION_HEIGHT * 0.82,
    borderWidth: 1,
    borderColor: "rgba(255, 168, 92, 0.35)",
    shadowOpacity: 0.28,
    shadowRadius: 20,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 10, width: 0 },
    elevation: 6,
    overflow: "hidden",
    position: "relative",
  },
  discoverCardBackground: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 0,
  },
  discoverCardBackgroundImage: {
    borderRadius: 24,
    height: "120%",
    transform: [{ translateY: -4,  }, { scale: 1.05 }],
  },
  matchesCardItem: {
    backgroundColor: SECONDARY_COLOR,
    paddingVertical: 7,
    paddingHorizontal: 20,
    borderRadius: 20,
  },
  matchesTextCardItem: {
    color: WHITE,
  },
  matchesTextCardItemDiscover: {
    color: DARK_GRAY,
  },
  descriptionCardItem: {
    color: GRAY,
    textAlign: "center",
    paddingHorizontal: 10,
  },
  descriptionCardItemDiscover: {
    textAlign: "center",
    paddingHorizontal: 18,
    marginTop: 6,
    fontFamily: SERIF_FONT,
  },
  status: {
    paddingBottom: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  statusText: {
    color: GRAY,
    fontSize: 12,
  },
  online: {
    width: 6,
    height: 6,
    backgroundColor: ONLINE_STATUS,
    borderRadius: 3,
    marginRight: 4,
  },
  offline: {
    width: 6,
    height: 6,
    backgroundColor: OFFLINE_STATUS,
    borderRadius: 3,
    marginRight: 4,
  },
  actionsCardItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 30,
  },
  actionsCardItemDiscover: {
    paddingVertical: 18,
    justifyContent: "space-between",
  },
  cardImageWrap: {
    position: "relative",
  },
  soulmateAvatarWrap: {
    width: 170,
    height: 170,
    borderRadius: 85,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  soulmateAvatarHalo: {
    position: "absolute",
    width: 180,
    height: 180,
    borderRadius: 90,
    top: -5,
    left: -5,
    zIndex: 0,
  },
  soulmateAvatarImage: {
    width: 150,
    height: 150,
    borderRadius: 75,
    zIndex: 1,
  },
  discoverImageWrap: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 22,
    marginTop: 6,
  },
  discoverAvatarWrap: {
    width: 348,
    height: 348,
    borderRadius: 174,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderColor: "transparent",
    shadowOpacity: 0.45,
    shadowRadius: 42,
    shadowColor: "rgba(255, 122, 26, 0.45)",
    shadowOffset: { height: 0, width: 0 },
    elevation: 6,
    position: "relative",
    overflow: "visible",
  },
  discoverAvatarHalo: {
    position: "absolute",
    width: 628,
    height: 642,
    top: -100,
    left: -140,
    zIndex: 2,
    opacity: 0.5,
  },
  discoverAvatarCore: {
    position: "absolute",
    width: 306,
    height: 306,
    borderRadius: 153,
    backgroundColor: "#F7EBDD",
    zIndex: 0,
  },
  discoverImage: {
    width: 400,
    height: 400,
    borderRadius: 200,
    marginTop: 100,
    borderWidth: 3,
    borderColor: "rgba(255, 228, 196, 0.95)",
    shadowOpacity: 0.28,
    shadowRadius: 18,
    shadowColor: BLACK,
    shadowOffset: { height: 8, width: 0 },
    zIndex: 1,
  },
  matchesCardOverlay: {
    position: "absolute",
    bottom: 12,
    alignSelf: "center",
  },
  discoverMatchesOverlay: {
    position: "absolute",
    top: 12,
    right: 12,
  },
  discoverMatchesPill: {
    backgroundColor: "rgba(255, 239, 220, 0.95)",
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 16,
  },
  discoverContent: {
    alignItems: "center",
    width: "100%",
    paddingHorizontal: 10,
  },
  discoverName: {
    color: TEXT_PRIMARY,
    fontSize: 22,
    lineHeight: 28,
    textAlign: "center",
    fontFamily: SERIF_FONT,
    fontWeight: "700",
    marginTop: 100,
    marginBottom: 6,
  },
  discoverLocation: {
    color: TEXT_SECONDARY,
    fontSize: 14,
    marginBottom: 2,
    fontFamily: SERIF_FONT,
  },
  discoverDescription: {
    textAlign: "center",
    paddingHorizontal: 18,
    marginTop: 4,
    color: TEXT_PRIMARY,
    fontSize: 13,
    lineHeight: 22,
    fontFamily: SERIF_FONT,
  },
  discoverTagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    marginTop: 8,
  },
  discoverTagPill: {
    backgroundColor: SURFACE_BUTTON,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 22,
    marginHorizontal: 6,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: GLOW_HIGHLIGHT,
  },
  discoverTagText: {
    color: TEXT_PRIMARY,
    fontSize: 13,
    fontFamily: SERIF_FONT,
  },
  discoverPromptPill: {
    marginTop: 8,
    backgroundColor: "#FFF7ED",
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 34,
    borderWidth: 1,
    borderColor: GLOW_HIGHLIGHT,
    width: "92%",
  },
  discoverPromptText: {
    color: TEXT_PRIMARY,
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
    fontFamily: SERIF_FONT,
  },
  discoverRitualRow: {
    marginTop: 14,
    width: "92%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  discoverRitualLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(243, 199, 159, 0.8)",
  },
  discoverRitualTitle: {
    marginHorizontal: 10,
    color: TEXT_PRIMARY,
    fontSize: 14,
    fontFamily: SERIF_FONT,
    fontWeight: "700",
  },
  discoverSparkleLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 1,
    zIndex: 2,
  },
  discoverSparkleImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
    opacity: 0.82,
    zIndex: 10,
  },
  discoverSparkleDot: {
    position: "absolute",
    backgroundColor: "rgba(255,255,255,0.8)",
    shadowOpacity: 0.6,
    shadowRadius: 6,
    shadowColor: GLOW_HIGHLIGHT,
    shadowOffset: { height: 0, width: 0 },
  },
  cardThumbRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 18,
    marginBottom: 10,
  },
  cardThumbWrap: {
    marginHorizontal: 8,
    borderRadius: 18,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255, 236, 214, 0.9)",
    backgroundColor: "rgba(255,255,255,0.6)",
  },
  cardThumb: {
    width: 78,
    height: 78,
    borderRadius: 18,
  },
  contactButton: {
    marginTop: 8,
    marginBottom: 4,
    backgroundColor: SURFACE_BUTTON,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: GLOW_HIGHLIGHT,
  },
  contactButtonDiscover: {
    alignSelf: "flex-start",
    marginTop: 12,
    marginBottom: 8,
    backgroundColor: CTA_PRIMARY,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 18,
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowColor: BLACK,
    shadowOffset: { height: 2, width: 0 },
  },
  contactButtonText: {
    color: TEXT_PRIMARY,
    fontSize: 13,
    fontFamily: SERIF_FONT,
    marginLeft: 6,
  },
  welcomeContainer: {
    flex: 1,
    paddingHorizontal: 20,
    justifyContent: "space-between",
  },
  welcomeTop: {
    paddingTop: 90,
    alignItems: "center",
  },
  welcomeHaloContainer: {
    width: 300,
    height: 300,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  welcomeHalo1: {
    position: "absolute",
    width: 250,
    height: 250,
    opacity: 0.8,
    zIndex: 1,
  },
  welcomeHalo2: {
    position: "absolute",
    width: 300,
    height: 300,
    opacity: 0.5,
    zIndex: 0,
  },
  welcomeTitle: {
    fontSize: 38,
    color: TEXT_PRIMARY,
    marginBottom: 6,
    fontWeight: "700",
    textShadowColor: "rgba(255,255,255,0.9)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  welcomeSubtitle: {
    fontSize: 14,
    color: TEXT_SECONDARY,
    textAlign: "center",
    maxWidth: 280,
  },
  welcomeCard: {
    backgroundColor: "rgba(255,255,255,0.0)",
    borderRadius: 22,
    paddingVertical: 22,
    paddingHorizontal: 20,
    marginTop: 30,
    alignItems: "center",
    borderWidth: 0,
    shadowOpacity: 0,
  },
  welcomeQuestion: {
    fontSize: 16,
    color: WHITE,
    textAlign: "center",
    marginTop: 6,
  },
  welcomeButtons: {
    marginTop: 22,
    width: "100%",
    gap: 16,
  },
  welcomeLogo: {
    alignContent: "center",
    justifyContent: "center",
    top: 50,

    opacity: 1,
    position: "absolute",
    width: DIMENSION_WIDTH,
    height: 180,
  },

  welcomePrimary: {
    backgroundColor: CTA_PRIMARY,
    paddingVertical: 14,
    borderRadius: 24,
    alignItems: "center",
    marginVertical: 22,
    borderWidth: 1,
    borderColor: "rgba(255, 238, 220, 0.7)",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 6, width: 0 },
    elevation: 3,
  },
  welcomePrimaryText: {
    color: WHITE,
    fontSize: 20,
    fontWeight: "500",
    fontFamily: SERIF_FONT,
  },
  welcomeSecondary: {
    backgroundColor: BUTTON_CREAM,
    paddingVertical: 14,
    borderRadius: 24,
    alignItems: "center",
    borderWidth: 1,
    borderColor: BUTTON_BORDER,
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 4, width: 0 },
    elevation: 2,
    marginBottom: 40,
  },
  welcomeSecondaryText: {
    color: TEXT_PRIMARY,
    fontSize: 20,
    fontWeight: "500",
    fontFamily: SERIF_FONT,
  },
  loginContainer: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  loginCard: {
    backgroundColor: WHITE,
    borderRadius: 22,
    paddingVertical: 24,
    paddingHorizontal: 20,
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowColor: BLACK,
    shadowOffset: { height: 8, width: 0 },
    zIndex: 1,
  },
  loginTitle: {
    fontSize: 22,
    color: PRIMARY_COLOR,
    fontWeight: "700",
    textAlign: "center",
  },
  loginSubtitle: {
    fontSize: 13,
    color: GRAY,
    textAlign: "center",
    marginTop: 6,
  },
  loginField: {
    marginTop: 16,
  },
  loginLabel: {
    fontSize: 12,
    color: PRIMARY_COLOR,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },
  loginInput: {
    backgroundColor: "#FFF1E6",
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    color: DARK_GRAY,
    fontSize: 14,
  },
  loginError: {
    marginTop: 12,
    color: DISLIKE_ACTIONS,
    textAlign: "center",
    fontSize: 12,
  },
  loginButton: {
    backgroundColor: CTA_PRIMARY,
    paddingVertical: 14,
    borderRadius: 24,
    alignItems: "center",
    marginTop: 18,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 6, width: 0 },
    elevation: 3,
  },
  loginButtonDisabled: {
    opacity: 0.6,
  },
  loginButtonText: {
    color: WHITE,
    fontSize: 16,
    fontWeight: "500",
    fontFamily: SERIF_FONT,
  },
  loginSecondary: {
    backgroundColor: BUTTON_CREAM,
    paddingVertical: 14,
    borderRadius: 24,
    alignItems: "center",
    marginTop: 12,
    borderWidth: 1,
    borderColor: BUTTON_BORDER,
    shadowOpacity: 0.14,
    shadowRadius: 10,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 4, width: 0 },
    elevation: 2,
  },
  loginSecondaryText: {
    color: TEXT_PRIMARY,
    fontSize: 16,
    fontWeight: "500",
    fontFamily: SERIF_FONT,
  },
  galleryOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.9)",
  },
  galleryClose: {
    position: "absolute",
    top: 50,
    right: 20,
    zIndex: 10,
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  gallerySlide: {
    width: DIMENSION_WIDTH,
    height: DIMENSION_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
  },
  galleryImage: {
    width: DIMENSION_WIDTH,
    height: DIMENSION_HEIGHT * 0.7,
    resizeMode: "contain",
  },
  contactOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "flex-end",
  },
  contactCard: {
    backgroundColor: WHITE,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 18,
    maxHeight: DIMENSION_HEIGHT * 0.7,
  },
  contactHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  contactTitle: {
    fontSize: 18,
    color: DARK_GRAY,
  },
  contactSectionTitle: {
    color: PRIMARY_COLOR,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginTop: 10,
    marginBottom: 6,
  },
  contactSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  contactRow: {
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#FFE1CC",
  },
  contactRowTitle: {
    color: DARK_GRAY,
    fontSize: 14,
  },
  contactRowMeta: {
    color: GRAY,
    fontSize: 12,
    marginTop: 2,
  },
  swipeBadgeLike: {
    position: "absolute",
    top: 160,
    left: 24,
    zIndex: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    borderWidth: 3,
    borderColor: "#2F8F83",
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  swipeBadgeTextLike: {
    fontSize: 28,
    fontWeight: "800",
    color: "#2F8F83",
    letterSpacing: 2,
  },
  swipeBadgeNope: {
    position: "absolute",
    top: 160,
    right: 24,
    zIndex: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    borderWidth: 3,
    borderColor: "#B76E5A",
    backgroundColor: "rgba(255,255,255,0.9)",
  },
  swipeBadgeTextNope: {
    fontSize: 28,
    fontWeight: "800",
    color: "#B76E5A",
    letterSpacing: 2,
  },
  swipeOverlay: {
    position: "absolute",
    top: 140,
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 20,
  },
  swipeIconWrap: {
    width: 90,
    height: 90,
    borderRadius: 45,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WHITE,
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowColor: BLACK,
    shadowOffset: { height: 8, width: 0 },
  },
  swipeText: {
    marginTop: 10,
    color: DARK_GRAY,
    fontSize: 14,
    backgroundColor: WHITE,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    overflow: "hidden",
    textAlign: "center",
  },
  vibeRow: {
    flexDirection: "row",
    marginTop: 6,
    marginBottom: 8,
    flexWrap: "wrap",
  },
  vibePill: {
    backgroundColor: SURFACE_BUTTON,
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 14,
    marginRight: 8,
    marginBottom: 6,
  },
  vibeText: {
    color: TEXT_PRIMARY,
    fontSize: 12,
  },
  promptLabel: {
    color: PRIMARY_COLOR,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginTop: 6,
  },
  promptText: {
    color: GRAY,
    textAlign: "center",
    paddingHorizontal: 12,
  },
  promptTextDiscover: {
    textAlign: "center",
    paddingHorizontal: 18,
    fontFamily: SERIF_FONT,
  },
  button: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: BUTTON_CREAM,
    borderWidth: 1,
    borderColor: BUTTON_BORDER,
    marginHorizontal: 7,
    alignItems: "center",
    justifyContent: "center",
    elevation: 1,
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 10, width: 0 },
  },
  miniButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: BUTTON_CREAM,
    borderWidth: 1,
    borderColor: BUTTON_BORDER,
    marginHorizontal: 7,
    alignItems: "center",
    justifyContent: "center",
    elevation: 1,
    shadowOpacity: 0.15,
    shadowRadius: 20,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 10, width: 0 },
  },

  // COMPONENT - CITY
  city: {
    backgroundColor: WHITE,
    padding: 10,
    borderRadius: 20,
    width: 100,
    elevation: 1,
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowColor: BLACK,
    shadowOffset: { height: 0, width: 0 },
  },
  cityText: {
    color: DARK_GRAY,
    fontSize: 13,
    textAlign: "center",
  },

  // COMPONENT - FILTERS
  filters: {
    backgroundColor: BUTTON_CREAM,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 24,
    minWidth: 140,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: BUTTON_BORDER,
    elevation: 1,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 5, width: 0 },
  },
  filtersRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  filtersIcon: {
    width: 26,
    height: 26,
    borderRadius: 12,
    backgroundColor: "#FFD9B5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  filtersLabel: {
    color: GRAY,
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  filtersValue: {
    color: DARK_GRAY,
    fontSize: 13,
    marginTop: 2,
  },
  filtersChevron: {
    marginLeft: 10,
  },

  // COMPONENT - MESSAGE
  containerMessage: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
    width: "100%",
  },
  avatar: {
    borderRadius: 30,
    width: 60,
    height: 60,
    marginRight: 20,
    marginVertical: 6,
  },
  message: {
    color: GRAY,
    fontSize: 12,
    paddingTop: 5,
  },
  messageName: {
    color: DARK_GRAY,
    fontSize: 16,
    fontWeight: "600",
  },

  // COMPONENT - PROFILE ITEM
  containerProfileItem: {
    backgroundColor: WHITE,
    paddingHorizontal: 10,
    paddingBottom: 25,
    margin: 20,
    borderRadius: 8,
    marginTop: -65,
    elevation: 1,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowColor: BLACK,
    shadowOffset: { height: 0, width: 0 },
  },
  matchesProfileItem: {
    width: 135,
    marginTop: -15,
    backgroundColor: SECONDARY_COLOR,
    paddingVertical: 7,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignSelf: "center",
  },
  matchesTextProfileItem: {
    color: WHITE,
    textAlign: "center",
  },
  name: {
    paddingTop: 25,
    paddingBottom: 5,
    color: DARK_GRAY,
    fontSize: 15,
    textAlign: "center",
  },
  descriptionProfileItem: {
    color: GRAY,
    textAlign: "center",
    paddingBottom: 20,
    fontSize: 13,
  },
  info: {
    paddingVertical: 8,
    flexDirection: "row",
    alignItems: "flex-start",
  },
  iconProfile: {
    fontSize: 12,
    color: DARK_GRAY,
    paddingHorizontal: 10,
  },
  infoContent: {
    color: GRAY,
    fontSize: 13,
    lineHeight: 18,
    flex: 1,
    flexWrap: "wrap",
  },
  profileSection: {
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#FFE1CC",
  },
  profileSectionTitle: {
    color: PRIMARY_COLOR,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 6,
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  profileRowTitle: {
    color: DARK_GRAY,
    fontSize: 14,
  },
  profileRowMeta: {
    color: GRAY,
    fontSize: 12,
    marginTop: 2,
  },
  profileBadge: {
    backgroundColor: "#FFE1CC",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  profileBadgeText: {
    color: DARK_GRAY,
    fontSize: 12,
  },

  // CONTAINER - GENERAL
  bg: {
    flex: 1,
    resizeMode: "cover",
    backgroundColor: BG_MAIN,
  },
  top: {
    paddingTop: 50,
    marginHorizontal: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  title: { paddingBottom: 10, fontSize: 22, color: TEXT_PRIMARY },
  meditatePill: {
    backgroundColor: BUTTON_CREAM,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    elevation: 1,
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 4, width: 0 },
    borderWidth: 1,
    borderColor: BUTTON_BORDER,
  },
  meditateText: {
    color: TEXT_PRIMARY,
    fontSize: 13,
    fontFamily: SERIF_FONT,
    marginLeft: 6,
  },

  // CONTAINER - HOME
  containerHome: {
    marginHorizontal: 10,
    flex: 1,
    paddingBottom: 90,
  },

  // CONTAINER - MATCHES
  containerMatches: {
    justifyContent: "space-between",
    flex: 1,
    paddingHorizontal: 10,
  },

  // CONTAINER - MESSAGES
  containerMessages: {
    justifyContent: "space-between",
    flex: 1,
    paddingHorizontal: 0,
  },
  matchScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  matchCard: {
    width: "100%",
    backgroundColor: "transparent",
    borderRadius: 0,
    paddingVertical: 16,
    paddingHorizontal: 8,
    alignItems: "center",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowColor: BLACK,
    shadowOffset: { height: 0, width: 0 },
  },
  matchHeartsLayer: {
    width: "100%",
    height: 70,
    position: "relative",
    marginBottom: 6,
  },
  matchHeart: {
    position: "absolute",
    backgroundColor: "rgba(255,255,255,0.9)",
    padding: 8,
    borderRadius: 20,
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowColor: BLACK,
    shadowOffset: { height: 4, width: 0 },
  },
  matchHeartLeft: {
    left: 10,
    top: 12,
  },
  matchHeartCenter: {
    position: "absolute",
    alignSelf: "center",
    top: 10,
    zIndex: 2,
  },
  matchHeartRight: {
    right: 10,
    top: 16,
  },
  matchTitle: {
    fontSize: 26,
    color: TEXT_PRIMARY,
    fontWeight: "600",
    fontFamily: SERIF_FONT,
    marginTop: -4,
  },
  matchSubtitle: {
    marginTop: 2,
    color: TEXT_SECONDARY,
    fontSize: 15,
    textAlign: "center",
    fontFamily: SERIF_FONT,
  },
  matchAvatarRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
    marginBottom: 14,
    position: "relative",
    height: 220,
  },
  matchAvatarRing: {
    width: 280,
    height: 280,
    borderRadius: 140,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderColor: "transparent",
    shadowOpacity: 0,
    shadowRadius: 0,
    shadowColor: "transparent",
    shadowOffset: { height: 0, width: 0 },
    elevation: 0,
    position: "relative",
  },
  matchAvatarRingRight: {
    marginLeft: -18,
    backgroundColor: "rgba(220, 230, 200, 0.35)",
  },
  matchAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 0,
    borderColor: "transparent",
    zIndex: 1,
  },
  matchAvatarHalo: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: 140,
    top: 0,
    left: 0,
    zIndex: 0,
  },
  matchActions: {
    width: "100%",
    marginTop: 6,
    alignItems: "center",
  },
  matchPrimaryButton: {
    backgroundColor: CTA_PRIMARY,
    paddingVertical: 14,
    borderRadius: 24,
    alignItems: "center",
    width: "100%",
    maxWidth: 320,
    shadowOpacity: 0.15,
    shadowRadius: 10,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 6, width: 0 },
    elevation: 3,
  },
  matchPrimaryButtonText: {
    color: WHITE,
    fontSize: 16,
    fontWeight: "500",
    fontFamily: SERIF_FONT,
    letterSpacing: 0.4,
  },
  matchSecondaryButton: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: BUTTON_BORDER,
    backgroundColor: BUTTON_CREAM,
    paddingVertical: 13,
    borderRadius: 24,
    alignItems: "center",
    width: "100%",
    maxWidth: 320,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 4, width: 0 },
    elevation: 2,
  },
  matchSecondaryButtonText: {
    color: TEXT_PRIMARY,
    fontSize: 15,
    fontWeight: "500",
    fontFamily: SERIF_FONT,
  },
  flowTop: {
    paddingTop: 50,
    paddingHorizontal: 16,
    paddingBottom: 6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#EFE6DA",
  },
  flowTopIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  flowTopCenter: {
    flex: 1,
    alignItems: "center",
  },
  flowSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 18,
    marginTop: 16,
  },
  flowSectionTitle: {
    color: "#2F8F83",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  flowSectionCount: {
    backgroundColor: "#2F8F83",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginLeft: 10,
  },
  flowSectionCountText: {
    color: WHITE,
    fontSize: 12,
    fontWeight: "700",
  },
  matchesRow: {
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  soulmateScreen: {
    flex: 1,
    paddingTop: 52,
  },
  soulmateHeader: {
    paddingHorizontal: 16,
    paddingBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  soulmateTitle: {
    color: TEXT_PRIMARY,
    fontSize: 18,
    fontFamily: SERIF_FONT,
    fontWeight: "600",
  },
  soulmateList: {
    paddingHorizontal: 16,
    paddingBottom: 110,
  },
  soulmateItem: {
    alignItems: "center",
    marginBottom: 22,
  },
  soulmateHaloWrap: {
    width: 280,
    height: 280,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  soulmateSparkles: {
    position: "absolute",
    width: 280,
    height: 180,
    top: 10,
    opacity: 0.9,
    zIndex: 0,
  },
  soulmateHalo: {
    position: "absolute",
    width: 280,
    height: 280,
    top: 0,
    zIndex: 1,
  },
  soulmateAvatar: {
    width: 220,
    height: 220,
    borderRadius: 110,
    zIndex: 2,
  },
  soulmateName: {
    marginTop: 6,
    color: TEXT_PRIMARY,
    fontSize: 20,
    fontFamily: SERIF_FONT,
    fontWeight: "600",
  },
  soulmateCity: {
    marginTop: 2,
    color: TEXT_SECONDARY,
    fontSize: 14,
    fontFamily: SERIF_FONT,
  },
  soulmateFooterButton: {
    position: "absolute",
    left: 20,
    right: 20,
    bottom: 22,
    backgroundColor: CTA_PRIMARY,
    borderRadius: 24,
    paddingVertical: 14,
    alignItems: "center",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 6, width: 0 },
    elevation: 3,
  },
  soulmateFooterText: {
    color: WHITE,
    fontSize: 16,
    fontFamily: SERIF_FONT,
    fontWeight: "500",
  },
  matchItem: {
    alignItems: "center",
    marginRight: 14,
  },
  matchAvatarWrap: {
    position: "relative",
  },
  matchDot: {
    position: "absolute",
    right: -2,
    bottom: 6,
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: WHITE,
  },
  matchName: {
    marginTop: 8,
    color: DARK_GRAY,
    fontSize: 13,
  },
  messageRow: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#EFE6DA",
  },
  chatHeader: {
    paddingTop: 50,
    paddingHorizontal: 16,
    paddingBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 1,
    borderBottomColor: "#FFE1CC",
  },
  chatHeaderCenter: {
    flexDirection: "row",
    alignItems: "center",
  },
  chatAvatarWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FFE1CC",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  chatName: {
    color: DARK_GRAY,
    fontSize: 16,
  },
  chatBody: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  chatMatchedText: {
    color: GRAY,
    fontSize: 12,
    textAlign: "center",
    marginBottom: 14,
  },
  chatBubbleLeft: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(199, 208, 184, 0.4)",
    borderRadius: 20,
    borderTopLeftRadius: 4,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 12,
    maxWidth: "75%",
  },
  chatBubbleTextLeft: {
    color: TEXT_PRIMARY,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: SERIF_FONT,
  },
  chatBubbleRight: {
    alignSelf: "flex-end",
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    borderRadius: 20,
    borderTopRightRadius: 4,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 12,
    maxWidth: "75%",
  },
  chatBubbleTextRight: {
    color: TEXT_PRIMARY,
    fontSize: 15,
    lineHeight: 22,
    fontFamily: SERIF_FONT,
  },
  chatSent: {
    color: WHITE,
    fontSize: 10,
    marginTop: 4,
    opacity: 0.8,
  },
  chatInputBar: {
    borderTopWidth: 1,
    borderTopColor: "#FFE1CC",
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: WHITE,
  },
  chatInputPlaceholder: {
    color: GRAY,
    fontSize: 13,
  },
  chatSend: {
    color: CTA_PRIMARY,
    fontSize: 12,
  },
  chatTools: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingVertical: 8,
    backgroundColor: WHITE,
  },
  chatToolButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: SURFACE_BUTTON,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: GLOW_HIGHLIGHT,
  },
  chatToolPill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: SURFACE_BUTTON,
  },
  chatToolText: {
    color: TEXT_PRIMARY,
    fontSize: 12,
  },
  chatHeaderNew: {
    paddingTop: 60,
    paddingBottom: 20,
    alignItems: "center",
    position: "relative",
  },
  chatBackButton: {
    position: "absolute",
    top: 60,
    left: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  chatAvatarDualWrap: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  chatAvatarWithHalo: {
    width: 140,
    height: 140,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    marginHorizontal: -20,
  },
  chatHaloLeft: {
    position: "absolute",
    width: 140,
    height: 140,
    zIndex: 0,
  },
  chatHaloRight: {
    position: "absolute",
    width: 140,
    height: 140,
    zIndex: 0,
  },
  chatAvatarLeft: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 3,
    borderColor: "rgba(255, 255, 255, 0.9)",
    zIndex: 1,
  },
  chatAvatarRight: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 3,
    borderColor: "rgba(255, 255, 255, 0.9)",
    zIndex: 1,
  },
  chatHeaderTitle: {
    fontSize: 20,
    color: TEXT_SECONDARY,
    fontFamily: SERIF_FONT,
    textAlign: "center",
  },
  chatInfoButton: {
    position: "absolute",
    top: 60,
    right: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    alignItems: "center",
    justifyContent: "center",
  },
  chatBodyNew: {
    flex: 1,
    paddingHorizontal: 20,
  },
  chatBodyContent: {
    paddingTop: 20,
    paddingBottom: 30,
  },
  chatInputBarNew: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    borderTopWidth: 1,
    borderTopColor: "rgba(220, 230, 200, 0.4)",
  },
  chatInputNew: {
    flex: 1,
    backgroundColor: "rgba(247, 237, 225, 0.8)",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 15,
    color: TEXT_PRIMARY,
    fontFamily: SERIF_FONT,
    maxHeight: 100,
  },
  chatSendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: PRIMARY_COLOR,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 2, width: 0 },
  },

  // CONTAINER - PROFILE
  containerProfile: { marginHorizontal: 0 },
  profileCalmContent: {
    paddingHorizontal: 24,
    paddingTop: 56,
    paddingBottom: 48,
  },
  profileAvatarWrap: {
    width: 86,
    height: 86,
    borderRadius: 43,
    backgroundColor: "#F7E6D9",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  profileAvatar: {
    width: 76,
    height: 76,
    borderRadius: 38,
  },
  profileHeader: {
    marginBottom: 18,
  },
  profileName: {
    fontSize: 30,
    color: DARK_GRAY,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  profileEssence: {
    marginTop: 10,
    fontSize: 15,
    lineHeight: 22,
    color: "#6F635E",
  },
  profileEssenceMuted: {
    marginTop: 6,
    fontSize: 14,
    lineHeight: 21,
    color: "#9B8F84",
  },
  profileValueRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 6,
    marginBottom: 18,
  },
  profileValuePill: {
    backgroundColor: SURFACE_BUTTON,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    marginRight: 10,
    marginBottom: 10,
  },
  profileValueText: {
    color: TEXT_PRIMARY,
    fontSize: 13,
    fontWeight: "600",
  },
  profilePracticeSection: {
    marginBottom: 26,
  },
  profileSectionLabel: {
    color: "#A08E82",
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
  },
  profileInfoRow: {
    flexDirection: "row",
    flexWrap: "wrap",
  },
  profileInfoPill: {
    backgroundColor: SURFACE_BUTTON,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 14,
    marginRight: 8,
    marginBottom: 8,
  },
  profileInfoText: {
    color: TEXT_SECONDARY,
    fontSize: 12,
  },
  profilePrimaryCta: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: CTA_PRIMARY,
    borderRadius: 24,
    paddingVertical: 12,
    marginBottom: 22,
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 5, width: 0 },
  },
  profilePrimaryCtaText: {
    color: WHITE,
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: 0.2,
    marginLeft: 8,
  },
  profileSecondaryActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
  },
  profileActionButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: SURFACE_BUTTON,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: GLOW_HIGHLIGHT,
  },
  containerMeditations: {
    flex: 1,
    paddingHorizontal: 10,
  },
  photo: {
    width: DIMENSION_WIDTH,
    height: 450,
  },
  topIconLeft: {
    paddingLeft: 20,
  },
  topIconRight: {
    paddingRight: 20,
  },
  actionsProfile: {
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
  },
  textButton: {
    fontSize: 15,
    color: WHITE,
    paddingLeft: 5,
  },
  circledButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: CTA_PRIMARY,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 5, width: 0 },
  },
  roundedButton: {
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 10,
    height: 50,
    borderRadius: 24,
    backgroundColor: BUTTON_CREAM,
    paddingHorizontal: 20,
    borderWidth: 1,
    borderColor: BUTTON_BORDER,
  },
  auraHeader: {
    paddingTop: 70,
    paddingBottom: 24,
    alignItems: "center",
  },
  auraAvatarWrap: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: "#FFE1CC",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: WHITE,
    position: "relative",
  },
  auraAvatar: {
    width: 108,
    height: 108,
    borderRadius: 54,
    zIndex: 1,
  },
  auraAvatarHalo: {
    position: "absolute",
    width: 120,
    height: 120,
    borderRadius: 60,
    top: 0,
    left: 0,
    zIndex: 0,
  },
  auraAvatarHalo2: {
    position: "absolute",
    width: 140,
    height: 140,
    borderRadius: 70,
    top: -10,
    left: -10,
    zIndex: -1,
    opacity: 0.6,
  },
  auraProgress: {
    marginTop: 10,
    backgroundColor: PRIMARY_COLOR,
    paddingVertical: 6,
    paddingHorizontal: 18,
    borderRadius: 18,
  },
  auraProgressText: {
    color: WHITE,
    fontSize: 12,
  },
  auraNameRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 12,
  },
  auraName: {
    color: DARK_GRAY,
    fontSize: 24,
    marginRight: 6,
  },
  auraVerified: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: PRIMARY_COLOR,
    alignItems: "center",
    justifyContent: "center",
  },
  auraActions: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 18,
  },
  auraActionItem: {
    alignItems: "center",
  },
  auraActionCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: GLOW_HIGHLIGHT,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: SURFACE_BUTTON,
  },
  auraActionLabel: {
    color: TEXT_PRIMARY,
    fontSize: 12,
    marginTop: 8,
  },
  auraScreenTitle: {
    fontSize: 32,
    color: TEXT_SECONDARY,
    textAlign: "center",
    marginTop: 60,
    marginBottom: 30,
    fontFamily: SERIF_FONT,
  },
  auraProfileCard: {
    marginHorizontal: 20,
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    borderRadius: 24,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 30,
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowColor: BLACK,
    shadowOffset: { height: 4, width: 0 },
  },
  auraProfileAvatarWrap: {
    width: 80,
    height: 80,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    marginRight: 16,
  },
  auraProfileHalo: {
    position: "absolute",
    width: 90,
    height: 90,
    opacity: 0.7,
  },
  auraProfileAvatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.9)",
  },
  auraProfileInfo: {
    flex: 1,
  },
  auraProfileName: {
    fontSize: 20,
    color: TEXT_PRIMARY,
    fontFamily: SERIF_FONT,
    fontWeight: "600",
  },
  auraProfileLocation: {
    fontSize: 15,
    color: TEXT_SECONDARY,
    marginTop: 2,
    fontFamily: SERIF_FONT,
  },
  auraEditButton: {
    backgroundColor: "rgba(247, 237, 225, 0.8)",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: GLOW_HIGHLIGHT,
  },
  auraEditButtonText: {
    color: TEXT_PRIMARY,
    fontSize: 14,
    fontFamily: SERIF_FONT,
  },
  auraMenuList: {
    marginHorizontal: 20,
    marginBottom: 30,
  },
  auraMenuItem: {
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 16,
    marginBottom: 2,
  },
  auraMenuItemLast: {
    marginBottom: 0,
  },
  auraMenuIconWrap: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  auraMenuLabel: {
    flex: 1,
    fontSize: 16,
    color: TEXT_PRIMARY,
    fontFamily: SERIF_FONT,
  },
  auraFooter: {
    alignItems: "center",
    paddingVertical: 30,
  },
  auraFooterTitle: {
    fontSize: 18,
    color: TEXT_SECONDARY,
    fontFamily: SERIF_FONT,
    marginBottom: 4,
  },
  auraFooterVersion: {
    fontSize: 14,
    color: TEXT_SECONDARY,
    fontFamily: SERIF_FONT,
  },
  auraCard: {
    marginHorizontal: 16,
    backgroundColor: WHITE,
    borderRadius: 20,
    padding: 18,
    alignItems: "center",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowColor: BLACK,
    shadowOffset: { height: 6, width: 0 },
  },
  auraCardTitle: {
    color: DARK_GRAY,
    fontSize: 18,
  },
  auraCardSubtitle: {
    color: GRAY,
    fontSize: 13,
    textAlign: "center",
    marginTop: 6,
  },
  auraDots: {
    flexDirection: "row",
    marginTop: 12,
    marginBottom: 16,
  },
  auraDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#E5D8F8",
    marginHorizontal: 4,
  },
  auraDotActive: {
    backgroundColor: CTA_PRIMARY,
  },
  auraCta: {
    backgroundColor: CTA_PRIMARY,
    borderRadius: 24,
    paddingVertical: 14,
    paddingHorizontal: 22,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 6, width: 0 },
    elevation: 3,
  },
  auraCtaText: {
    color: WHITE,
    fontSize: 16,
    fontFamily: SERIF_FONT,
  },
  auraSettingsSection: {
    marginTop: 18,
    marginHorizontal: 16,
    backgroundColor: WHITE,
    borderRadius: 20,
    paddingVertical: 8,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowColor: BLACK,
    shadowOffset: { height: 4, width: 0 },
  },
  auraSettingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#FFE1CC",
  },
  auraSettingRowLast: {
    borderBottomWidth: 0,
  },
  auraSettingLabel: {
    color: DARK_GRAY,
    fontSize: 14,
  },

  // SETTINGS
  settingsContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 60,
  },
  settingsSection: {
    marginBottom: 18,
  },
  settingsSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  settingsSectionTitle: {
    color: TEXT_PRIMARY,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
  },
  settingsTag: {
    backgroundColor: CTA_PRIMARY,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  settingsTagText: {
    color: WHITE,
    fontSize: 10,
  },
  settingsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  settingsTitle: {
    color: DARK_GRAY,
    fontSize: 18,
  },
  settingsCard: {
    backgroundColor: WHITE,
    borderRadius: 20,
    paddingVertical: 8,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowColor: BLACK,
    shadowOffset: { height: 4, width: 0 },
  },
  settingsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#FFE1CC",
  },
  settingsRowLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  settingsRowRight: {
    flexDirection: "row",
    alignItems: "center",
  },
  settingsRowLast: {
    borderBottomWidth: 0,
  },
  settingsLabel: {
    color: DARK_GRAY,
    fontSize: 14,
    marginLeft: 8,
  },
  settingsAdd: {
    color: GRAY,
    fontSize: 12,
    marginRight: 6,
  },
  preferenceCard: {
    backgroundColor: WHITE,
    borderRadius: 18,
    padding: 16,
    marginTop: 16,
  },
  preferenceText: {
    color: DARK_GRAY,
    fontSize: 14,
    marginBottom: 12,
  },
  preferenceEmphasis: {
    color: PRIMARY_COLOR,
    fontWeight: "600",
  },

  // ONBOARDING
  onboardContainer: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 50,
    paddingBottom: 24,
  },
  onboardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  onboardProgressTrack: {
    flex: 1,
    height: 4,
    backgroundColor: "#FFE1CC",
    borderRadius: 2,
    marginHorizontal: 12,
    overflow: "hidden",
  },
  onboardProgressFill: {
    height: 4,
    backgroundColor: PRIMARY_COLOR,
  },
  onboardSkip: {
    color: PRIMARY_COLOR,
    fontSize: 12,
  },
  onboardTitle: {
    color: DARK_GRAY,
    fontSize: 24,
    marginBottom: 10,
  },
  onboardSubtitle: {
    color: GRAY,
    fontSize: 12,
    marginBottom: 12,
  },
  onboardOptions: {
    marginTop: 8,
  },
  onboardOption: {
    borderWidth: 1,
    borderColor: "#FFE1CC",
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 12,
    backgroundColor: WHITE,
  },
  onboardOptionActive: {
    borderColor: PRIMARY_COLOR,
    backgroundColor: "#FFE1CC",
  },
  onboardOptionText: {
    color: DARK_GRAY,
    fontSize: 14,
    textAlign: "center",
  },
  onboardOptionTextActive: {
    color: PRIMARY_COLOR,
  },
  onboardList: {
    marginTop: 8,
  },
  onboardListItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#FFE1CC",
  },
  onboardListText: {
    color: DARK_GRAY,
    fontSize: 14,
  },
  onboardCheck: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "#FFE1CC",
  },
  onboardCheckActive: {
    backgroundColor: CTA_PRIMARY,
    borderColor: CTA_PRIMARY,
  },
  onboardFooter: {
    marginTop: "auto",
  },
  onboardNext: {
    backgroundColor: CTA_PRIMARY,
    borderRadius: 24,
    paddingVertical: 14,
    alignItems: "center",
    shadowOpacity: 0.16,
    shadowRadius: 10,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 5, width: 0 },
    elevation: 2,
  },
  onboardNextDisabled: {
    backgroundColor: GLOW_HIGHLIGHT,
  },
  onboardNextText: {
    color: WHITE,
    fontSize: 16,
    fontFamily: SERIF_FONT,
  },
  meditationList: {
    paddingBottom: 110,
  },
  meditationCard: {
    backgroundColor: WHITE,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 1,
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowColor: BLACK,
    shadowOffset: { height: 6, width: 0 },
  },
  meditationTitle: {
    color: DARK_GRAY,
    fontSize: 16,
  },
  meditationMeta: {
    color: GRAY,
    fontSize: 12,
    marginTop: 4,
  },
  meditationPlay: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: SURFACE_BUTTON,
    alignItems: "center",
    justifyContent: "center",
  },
  meditationBottomBar: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 18,
    height: 62,
    borderRadius: 20,
    backgroundColor: WHITE,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowColor: BLACK,
    shadowOffset: { height: 8, width: 0 },
  },
  meditationPlayerDock: {
    position: "absolute",
    left: 16,
    right: 16,
    bottom: 18,
  },
  meditationBarButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 14,
  },
  meditationBarText: {
    color: DARK_GRAY,
    fontSize: 12,
    marginLeft: 6,
  },
  meditationBarPrimary: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: CTA_PRIMARY,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 18,
  },
  meditationBarPrimaryText: {
    color: WHITE,
    fontSize: 13,
    marginLeft: 6,
  },
  meditationPlayer: {
    backgroundColor: WHITE,
    borderRadius: 22,
    padding: 16,
    shadowOpacity: 0.18,
    shadowRadius: 16,
    shadowColor: BLACK,
    shadowOffset: { height: 8, width: 0 },
  },
  meditationPlayerHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  meditationPlayerInfo: {
    flex: 1,
    paddingRight: 12,
  },
  meditationPlayerLabel: {
    color: GRAY,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  meditationPlayerTitle: {
    color: DARK_GRAY,
    fontSize: 16,
    marginTop: 6,
  },
  meditationPlayerMeta: {
    color: GRAY,
    fontSize: 12,
    marginTop: 4,
  },
  meditationPlayerOpen: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: PRIMARY_COLOR,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 16,
  },
  meditationPlayerOpenText: {
    color: WHITE,
    fontSize: 12,
    marginLeft: 6,
  },
  meditationPlayerProgress: {
    marginTop: 12,
  },
  meditationPlayerTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: "#F3E6DC",
    overflow: "hidden",
  },
  meditationPlayerFill: {
    height: 6,
    borderRadius: 999,
    backgroundColor: PRIMARY_COLOR,
  },
  meditationPlayerControls: {
    marginTop: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  meditationPlayerControl: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E6D8CE",
    alignItems: "center",
    justifyContent: "center",
    marginHorizontal: 12,
  },
  meditationPlayerMain: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: PRIMARY_COLOR,
    alignItems: "center",
    justifyContent: "center",
  },

  // PREMIUM
  premiumContainer: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 60,
  },
  premiumHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  premiumBrand: {
    color: PRIMARY_COLOR,
    fontSize: 18,
    marginLeft: 8,
    fontWeight: "600",
  },
  premiumTitle: {
    color: DARK_GRAY,
    fontSize: 20,
    lineHeight: 28,
  },
  premiumSectionLabel: {
    color: GRAY,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginTop: 18,
    marginBottom: 10,
  },
  premiumPlans: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  premiumPlanCard: {
    width: "48%",
    backgroundColor: WHITE,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: "#FFE1CC",
  },
  premiumPlanActive: {
    borderColor: PRIMARY_COLOR,
  },
  premiumPlanTitle: {
    color: DARK_GRAY,
    fontSize: 16,
  },
  premiumPlanPrice: {
    color: GRAY,
    fontSize: 12,
    marginTop: 6,
  },
  premiumPlanCheck: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#FFE1CC",
    alignItems: "center",
    justifyContent: "center",
  },
  premiumPlanBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: PRIMARY_COLOR,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  premiumPlanBadgeText: {
    color: WHITE,
    fontSize: 10,
  },
  premiumList: {
    backgroundColor: WHITE,
    borderRadius: 16,
    padding: 14,
    marginTop: 16,
  },
  premiumListItem: {
    color: DARK_GRAY,
    fontSize: 13,
    marginBottom: 8,
  },
  premiumCta: {
    marginTop: 18,
    backgroundColor: CTA_PRIMARY,
    paddingVertical: 14,
    borderRadius: 24,
    alignItems: "center",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 6, width: 0 },
    elevation: 3,
  },
  premiumCtaText: {
    color: WHITE,
    fontSize: 16,
    fontFamily: SERIF_FONT,
  },

  // EDIT PROFILE
  editContainer: {
    flex: 1,
    paddingHorizontal: 16,
  },
  editSection: {
    marginTop: 18,
  },
  editSectionTitle: {
    color: PRIMARY_COLOR,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
  },
  mediaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  mediaSlot: {
    width: "31%",
    aspectRatio: 3 / 4,
    borderRadius: 12,
    marginBottom: 12,
    overflow: "hidden",
    backgroundColor: "rgba(255,255,255,0.6)",
  },
  mediaImage: {
    width: "100%",
    height: "100%",
  },
  mediaPlaceholder: {
    flex: 1,
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "rgba(91,45,139,0.4)",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.5)",
  },
  mediaAdd: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: PRIMARY_COLOR,
    alignItems: "center",
    justifyContent: "center",
  },
  mediaRemove: {
    position: "absolute",
    right: 6,
    bottom: 6,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center",
    justifyContent: "center",
  },
  editPrimaryButton: {
    marginTop: 6,
    backgroundColor: CTA_PRIMARY,
    borderRadius: 24,
    paddingVertical: 14,
    alignItems: "center",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 6, width: 0 },
    elevation: 3,
  },
  editPrimaryText: {
    color: WHITE,
    fontSize: 16,
    fontFamily: SERIF_FONT,
  },
  editRow: {
    backgroundColor: WHITE,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  editRowTitle: {
    color: DARK_GRAY,
    fontSize: 14,
  },
  editRowMeta: {
    color: GRAY,
    fontSize: 12,
    marginTop: 3,
  },
  editRowAction: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: SURFACE_BUTTON,
    alignItems: "center",
    justifyContent: "center",
  },
  editOutlineButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: GLOW_HIGHLIGHT,
    backgroundColor: WHITE,
    borderRadius: 24,
    paddingVertical: 12,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowColor: BLACK,
    shadowOffset: { height: 4, width: 0 },
    elevation: 2,
  },
  editOutlineText: {
    color: TEXT_PRIMARY,
    fontSize: 15,
    fontFamily: SERIF_FONT,
    marginLeft: 6,
  },

  // MENU
  tabButtonText: {
    letterSpacing: 0.2,
    fontSize: 12,
    textAlign: "center",
    top: -10,
    
  },
  iconMenu: {
    alignItems: "center",
  },
  tabBarWrapper: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 12,
    alignItems: "center",
  },
  tabBarContainer: {
    width: "90%",
    height: 64,
    backgroundColor: "rgba(255, 244, 232, 0.28)",
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    shadowOpacity: 0.2,
    shadowRadius: 16,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 8, width: 0 },
    borderWidth: 1,
    borderColor: "rgba(255, 168, 92, 0.35)",
    paddingHorizontal: 8,
  },
  tabItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
  },
  tabBump: {
    display: "none",
    position: "absolute",
    top: -14,
    width: 60,
    height: 82,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: "rgba(255, 244, 232, 0.58)",
  },
  tabCircle: {
    top: -10,
    width: 52,
    height: 52,
    borderRadius: 26,
    opacity: 0.9,
    backgroundColor: PRIMARY_COLOR,
    alignItems: "center",
    justifyContent: "center",
    shadowOpacity: 0.24,
    shadowRadius: 10,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 5, width: 0 },
  },
  // EVENTS SCREEN
  eventsContainer: {
    flex: 1,
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  eventsTitle: {
    fontSize: 32,
    fontWeight: "600",
    color: TEXT_PRIMARY,
    textAlign: "center",
    marginBottom: 20,
    fontFamily: SERIF_FONT,
  },
  eventsSearchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.7)",
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "rgba(220, 220, 220, 0.5)",
  },
  eventsSearchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 16,
    color: TEXT_PRIMARY,
  },
  eventsListContent: {
    paddingBottom: 100,
  },
  eventCard: {
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    borderRadius: 20,
    marginBottom: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(220, 220, 220, 0.3)",
  },
  eventCardImage: {
    width: "100%",
    height: 180,
  },
  eventCardContent: {
    padding: 16,
  },
  eventCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 6,
  },
  eventCardTitle: {
    fontSize: 22,
    fontWeight: "600",
    color: TEXT_PRIMARY,
    flex: 1,
    marginRight: 10,
    fontFamily: SERIF_FONT,
  },
  eventCardAttendees: {
    fontSize: 16,
    color: TEXT_SECONDARY,
    fontWeight: "500",
  },
  eventCardSubtitle: {
    fontSize: 15,
    color: TEXT_SECONDARY,
    marginBottom: 12,
  },
  eventCardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  eventCardDate: {
    fontSize: 15,
    color: TEXT_SECONDARY,
  },
  eventCardButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 24,
    backgroundColor: BUTTON_CREAM,
    borderWidth: 1,
    borderColor: BUTTON_BORDER,
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 3, width: 0 },
  },
  eventCardButtonText: {
    fontSize: 15,
    color: TEXT_SECONDARY,
    marginRight: 4,
  },
  // EVENT DETAIL SCREEN
  eventDetailContainer: {
    flex: 1,
    backgroundColor: "rgba(247, 237, 225, 0.96)",
  },
  eventDetailHeroImage: {
    width: "100%",
    height: 320,
  },
  eventDetailHeader: {
    position: "absolute",
    top: 50,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    zIndex: 10,
  },
  eventDetailBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  eventDetailMenuButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0, 0, 0, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  eventDetailContent: {
    flex: 1,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  eventDetailTitle: {
    fontSize: 32,
    fontWeight: "600",
    color: TEXT_PRIMARY,
    marginBottom: 12,
    fontFamily: SERIF_FONT,
  },
  eventDetailDescription: {
    fontSize: 17,
    lineHeight: 26,
    color: TEXT_SECONDARY,
    marginBottom: 24,
  },
  eventDetailHostSection: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 24,
  },
  eventDetailHostAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 12,
  },
  eventDetailHostName: {
    fontSize: 18,
    color: TEXT_PRIMARY,
    fontWeight: "500",
  },
  eventDetailInfoSection: {
    marginBottom: 32,
  },
  eventDetailInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  eventDetailInfoText: {
    fontSize: 16,
    color: TEXT_SECONDARY,
    marginLeft: 12,
  },
  eventDetailJoinButton: {
    backgroundColor: CTA_PRIMARY,
    borderRadius: 24,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 12,
    shadowOpacity: 0.2,
    shadowRadius: 12,
    shadowColor: PRIMARY_COLOR,
    shadowOffset: { height: 6, width: 0 },
  },
  eventDetailJoinButtonText: {
    fontSize: 18,
    fontWeight: "600",
    color: WHITE,
    fontFamily: SERIF_FONT,
  },
  eventDetailJoinNote: {
    fontSize: 14,
    color: TEXT_SECONDARY,
    textAlign: "center",
    marginBottom: 40,
  },
  // EVENT CHAT SCREEN
  eventChatBackground: {
    flex: 1,
  },
  eventChatHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 50,
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: "rgba(247, 237, 225, 0.95)",
  },
  eventChatBackButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  eventChatHeaderInfo: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 8,
  },
  eventChatHeaderLogo: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 8,
  },
  eventChatHeaderTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: TEXT_PRIMARY,
  },
  eventChatHeaderSubtitle: {
    fontSize: 14,
    color: TEXT_SECONDARY,
  },
  eventChatMenuButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  eventChatParticipantsSection: {
    alignItems: "center",
    paddingVertical: 24,
    paddingHorizontal: 20,
  },
  eventChatParticipants: {
    flexDirection: "row",
    marginBottom: 16,
  },
  eventChatParticipantAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: WHITE,
  },
  eventChatDescription: {
    fontSize: 16,
    lineHeight: 24,
    color: TEXT_PRIMARY,
    textAlign: "center",
    marginBottom: 20,
  },
  eventChatTags: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 16,
  },
  eventChatTag: {
    flexDirection: "row",
    alignItems: "center",
  },
  eventChatTagIcon: {
    fontSize: 18,
    marginRight: 6,
  },
  eventChatTagText: {
    fontSize: 15,
    color: TEXT_SECONDARY,
  },
  eventChatMessagesContainer: {
    flex: 1,
  },
  eventChatMessagesContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
  },
  eventChatMessageBubble: {
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
  },
  eventChatMessageSender: {
    fontSize: 15,
    fontWeight: "600",
    color: TEXT_PRIMARY,
    marginBottom: 8,
  },
  eventChatMessageTime: {
    fontSize: 13,
    fontWeight: "400",
    color: TEXT_SECONDARY,
  },
  eventChatMessageText: {
    fontSize: 15,
    lineHeight: 22,
    color: TEXT_PRIMARY,
  },
  eventChatInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "rgba(247, 237, 225, 0.95)",
    borderTopWidth: 1,
    borderTopColor: "rgba(220, 220, 220, 0.3)",
  },
  eventChatAttachButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  eventChatInput: {
    flex: 1,
    backgroundColor: WHITE,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 15,
    color: TEXT_PRIMARY,
    marginHorizontal: 8,
  },
  eventChatSendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#8F9F86",
    alignItems: "center",
    justifyContent: "center",
  },
});
