import { StyleSheet } from "react-native";
import { vibesTheme } from "../../src/theme/vibesTheme";
const c = vibesTheme.colors;
export const dayStyles = StyleSheet.create({
  plain: {
    gap: 12,
  },
  card: {
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.accentBlue,
    borderRadius: 20,
    padding: 16,
    gap: 12,
  },
  title: { color: c.primaryText, fontSize: 21, fontWeight: "600" },
  text: { color: c.primaryText, fontSize: 16, lineHeight: 23 },
  hint: { color: c.secondaryText, fontSize: 14, lineHeight: 20 },
  error: {
    color: c.primaryText,
    backgroundColor: c.accentCoral,
    borderRadius: 10,
    padding: 12,
  },
  row: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap" },
  mediaSection: {
    gap: 4,
    marginTop: 2,
  },
  sectionTitle: {
    color: c.primaryText,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "600",
  },
  mediaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  mediaButton: {
    flexGrow: 0,
    flexShrink: 1,
    width: "48%",
    borderRadius: 18,
    minHeight: 58,
    paddingHorizontal: 8,
  },
  mediaButtonText: {
    fontSize: 14,
    lineHeight: 18,
    textAlign: "center",
  },
  linkBox: {
    borderWidth: 1,
    borderColor: c.accentBlue,
    borderRadius: 18,
    backgroundColor: c.surface,
    padding: 12,
    gap: 10,
  },
  linkInput: {
    color: c.primaryText,
    backgroundColor: c.background,
    borderColor: c.secondaryText,
    borderWidth: 1,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    minHeight: 50,
  },
  linkButton: {
    borderRadius: 18,
    minHeight: 52,
  },
  footerActions: {
    gap: 12,
    marginTop: 4,
  },
  between: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  button: {
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 16,
    backgroundColor: c.accentBlue,
    alignItems: "center",
    justifyContent: "center",
  },
  primary: { backgroundColor: c.accentMustard },
  secondary: {
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.secondaryText,
  },
  danger: { backgroundColor: c.accentCoral },
  buttonText: {
    color: c.background,
    fontSize: 15,
    textAlign: "center",
  },
  secondaryButtonText: {
    color: c.primaryText,
  },
  disabled: { opacity: 0.4 },
  input: {
    color: c.primaryText,
    backgroundColor: c.surface,
    borderColor: c.secondaryText,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    fontSize: 16,
    minHeight: 48,
  },
  sheet: { flex: 1, backgroundColor: c.background },
  image: { width: "100%", height: 220, borderRadius: 12 },
  fullImage: { flex: 1, width: "100%" },
  content: { padding: 20, gap: 16, paddingBottom: 40 },
});
